---
- hosts: all
  sudo: yes
  vars:
    cluster_name:  EAR_Cluster
    vagrant_ip: 192.168.10.11
    seeds: 192.168.10.11
#    spark_version: spark-1.4.0-bin-hadoop2.4
    spark_version: spark-1.5.0-bin-hadoop2.4
    connector_jar: spark-cassandra-connector-assembly-1.4.0-M1-SNAPSHOT.jar 
    scala_version: "2.10"
    zookeeper_version: "3.4.6"
    kafka_version: "0.8.2.1"
    lucene_plugin_version: "2.1.8.1"

  tasks:
  - name: install htop
    apt: name=htop state=present

  roles:
    - cassandra
    - opscenter
    - spark
    - kafka
#    - { role: mysql, tags: [ 'mysql' ] }

  tasks:
    - name: start a spark master
      command: nohup /opt/{{ spark_version }}/sbin/start-master.sh
      tags:
        - spark

    - name: start a spark worker
      command: nohup /opt/{{ spark_version }}/bin/spark-class org.apache.spark.deploy.worker.Worker  spark://{{ vagrant_ip }}:7077
      async: 315360000
      poll: 0
      tags:
        - spark
