- name: Extract Zookeeper {{ zookeeper_version }}
  copy: src=./zookeeper-{{ zookeeper_version }}.tar.gz dest=/tmp/zookeeper-{{ zookeeper_version }}.tar.gz owner=vagrant group=vagrant mode=0644 force=no
  
- name: Unpack the tar
  shell: tar -xzvf /tmp/zookeeper-{{ zookeeper_version }}.tar.gz chdir=/tmp/ creates=/tmp/zookeeper-{{ zookeeper_version }}
  
- name: Copy configuration over
  template: src=zoo.cfg dest=/tmp/zookeeper-{{ zookeeper_version }}/conf/ mode=0644
  
- name: Copy zookeeper to real destination
  shell: mv /tmp/zookeeper-{{ zookeeper_version }} /usr/local/zookeeper-{{ zookeeper_version }} creates=/usr/local/zookeeper-{{ zookeeper_version }}
  
- name: Link /usr/local/zookeeper to this version
  shell: ln -s zookeeper-{{ zookeeper_version }} zookeeper chdir=/usr/local creates=/usr/local/zookeeper
  
- name: Install the Zookeeper service handler
  template: src=zookeeper dest=/etc/init.d/ mode=0755

- name: Run the Zookeeper service
  service: name=zookeeper state=started enabled=yes
  
  
  


